// Generated by CoffeeScript 1.6.3
(function() {
  var deobfuscateElem;

  deobfuscateElem = function(str) {
    var c, chrs, _i, _len;
    chrs = str.split(',');
    for (_i = 0, _len = chrs.length; _i < _len; _i++) {
      c = chrs[_i];
      res += String.fromCharCode((new Number(c)) - 23);
    }
    return res;
  };

  $(document).ready(function() {
    return $(".obf").each(function(i, e) {
      var $e, val;
      $e = $(e);
      val = deobfuscateElem($e.html());
      $e.html(val);
      return $e.attr('href', "mailto:" + val);
    });
  });

}).call(this);
